name: Crusher Test

on:
  pull_request:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g crusher-cli@1.3.27

    - uses: akhileshns/heroku-deploy@v3.3.6 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "crusher-test"
        heroku_email: "utkarshdix02@gmail.com"

    - name: RUN CLI Checks
      run: npx crusher-cli run --endpoint=https://cc3966b2f5ac.ngrok.io --project_id=58  --crusher_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2MCwidGVhbV9pZCI6NDQsImlhdCI6MTU5NjAzNTQyOCwiZXhwIjo1MTk2MDMxODI4fQ.kL-_iI3l3R5u2Q1FzHDDWg6ENHn31K_4vqo89ysFRhI
